server:
  port: 8765


spring:
  application:
    name: ApiGateWay
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://localhost:8099
          predicates:
            - Path=/reserve/**
        - id: buy
          uri: http://localhost:8098
          predicates:
            - Path=/buy/**




